// GENERATED by scripts/gen-menu.mjs from docs/MENU-DATA.md. Do not edit by hand.
export type TrayId = 'nasi' | 'kuah' | 'roti' | 'goreng' | 'laut' | 'minum'
export interface Dish { slug: string; en: string; ms: string; tray: TrayId; protein: string[]; heat: 1 | 2 | 3 | 4 | 5; signature: boolean; story: string; pairs: string[]; price: string; source: string; verify: string[] }
export const TRAYS: { id: TrayId; label: string }[] = [
  { id: 'nasi', label: 'Nasi & Rice' }, { id: 'kuah', label: 'Curries (Kuah)' }, { id: 'roti', label: 'Murtabak & Roti' },
  { id: 'goreng', label: 'Fried (Goreng)' }, { id: 'laut', label: 'Seafood' }, { id: 'minum', label: 'Drinks' },
]
export const DISHES: Dish[] = [
  {
    "slug": "murtabak",
    "en": "Murtabak",
    "ms": "Murtabak",
    "tray": "roti",
    "protein": [
      "chicken",
      "mutton"
    ],
    "heat": 2,
    "signature": true,
    "story": "Folded on the hot griddle at the front door; in full view of the queue.",
    "pairs": [
      "kari-daging",
      "dalca"
    ],
    "price": "Ask at counter",
    "source": "S1, S3, S6, S8, S9",
    "verify": []
  },
  {
    "slug": "ayam-bawang",
    "en": "Chicken with onion",
    "ms": "Ayam Bawang",
    "tray": "kuah",
    "protein": [
      "chicken"
    ],
    "heat": 2,
    "signature": true,
    "story": "Fried chicken simmered in a slow, sweet onion gravy: an easy first plate.",
    "pairs": [
      "nasi-kandar",
      "kuah-campur"
    ],
    "price": "Ask at counter",
    "source": "S8, B",
    "verify": []
  },
  {
    "slug": "mutton-kurma",
    "en": "Mutton kurma",
    "ms": "Kurma Kambing",
    "tray": "kuah",
    "protein": [
      "mutton"
    ],
    "heat": 1,
    "signature": true,
    "story": "Mild, thick and pale: one of the house signatures.",
    "pairs": [
      "nasi-briyani",
      "murtabak"
    ],
    "price": "Ask at counter",
    "source": "S3, S6",
    "verify": []
  },
  {
    "slug": "kari-ketam",
    "en": "Crab curry",
    "ms": "Kari Ketam",
    "tray": "laut",
    "protein": [
      "seafood"
    ],
    "heat": 4,
    "signature": true,
    "story": "Whole crab in a deep red kuah.",
    "pairs": [
      "nasi-kandar",
      "telur-rebus"
    ],
    "price": "Ask at counter",
    "source": "B",
    "verify": []
  },
  {
    "slug": "nasi-kandar",
    "en": "Nasi kandar (steamed rice)",
    "ms": "Nasi Kandar",
    "tray": "nasi",
    "protein": [
      "vegetarian"
    ],
    "heat": 1,
    "signature": false,
    "story": "The plate it all starts on: rice first, then your pieces, then the kuah.",
    "pairs": [
      "kuah-campur",
      "ayam-kapitan"
    ],
    "price": "Ask at counter",
    "source": "S1, S4, S5",
    "verify": []
  },
  {
    "slug": "kuah-campur",
    "en": "Mixed gravies over rice",
    "ms": "Kuah Campur (\"banjir\")",
    "tray": "nasi",
    "protein": [
      "vegetarian"
    ],
    "heat": 3,
    "signature": false,
    "story": "Ask for a ladle of several curries over your rice. Regulars call a full flood *banjir*.",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "Nasi kandar ordering custom (SPEC §6 H6).",
    "verify": []
  },
  {
    "slug": "nasi-briyani",
    "en": "Biryani rice",
    "ms": "Nasi Briyani",
    "tray": "nasi",
    "protein": [
      "vegetarian"
    ],
    "heat": 2,
    "signature": false,
    "story": "Bright orange grains, cooked the old-fashioned way.",
    "pairs": [
      "mutton-kurma",
      "ayam-goreng"
    ],
    "price": "Ask at counter",
    "source": "S1, S3, S6",
    "verify": []
  },
  {
    "slug": "briyani-ayam-goreng",
    "en": "Biryani with fried chicken",
    "ms": "Nasi Briyani Ayam Goreng",
    "tray": "nasi",
    "protein": [
      "chicken"
    ],
    "heat": 2,
    "signature": false,
    "story": "Fragrant biryani topped with crisp spiced chicken.",
    "pairs": [
      "kuah-campur"
    ],
    "price": "Ask at counter",
    "source": "S9",
    "verify": []
  },
  {
    "slug": "nasi-tomato",
    "en": "Tomato rice",
    "ms": "Nasi Tomato",
    "tray": "nasi",
    "protein": [
      "vegetarian"
    ],
    "heat": 1,
    "signature": false,
    "story": "Tomato-tinted rice, a softer base than biryani.",
    "pairs": [
      "kari-itik"
    ],
    "price": "Ask at counter",
    "source": "S7",
    "verify": []
  },
  {
    "slug": "telur-rebus",
    "en": "Hard-boiled egg",
    "ms": "Telur Rebus",
    "tray": "nasi",
    "protein": [
      "egg"
    ],
    "heat": 1,
    "signature": false,
    "story": "A classic side; part of the old 20-to-30-sen plate.",
    "pairs": [
      "kari-ketam",
      "kari-ikan"
    ],
    "price": "Ask at counter",
    "source": "S5",
    "verify": []
  },
  {
    "slug": "bendi",
    "en": "Boiled okra",
    "ms": "Bendi Rebus",
    "tray": "nasi",
    "protein": [
      "vegetarian"
    ],
    "heat": 1,
    "signature": false,
    "story": "Ladies' fingers; part of the old 20-to-30-sen plate.",
    "pairs": [
      "kari-ikan"
    ],
    "price": "Ask at counter",
    "source": "S5",
    "verify": []
  },
  {
    "slug": "ayam-kapitan",
    "en": "Kapitan chicken",
    "ms": "Kari Ayam Kapitan",
    "tray": "kuah",
    "protein": [
      "chicken"
    ],
    "heat": 3,
    "signature": false,
    "story": "A thick, rich chicken curry; its spice mix is a family recipe.",
    "pairs": [
      "nasi-kandar",
      "nasi-briyani"
    ],
    "price": "Ask at counter",
    "source": "S1, S3, S5, S6, S7",
    "verify": []
  },
  {
    "slug": "kari-ayam",
    "en": "Chicken curry",
    "ms": "Kari Ayam",
    "tray": "kuah",
    "protein": [
      "chicken"
    ],
    "heat": 3,
    "signature": false,
    "story": "The everyday curry whose spice blend, the family says, hasn't changed in 100 years.",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S3",
    "verify": []
  },
  {
    "slug": "kari-daging",
    "en": "Beef curry",
    "ms": "Kari Daging",
    "tray": "kuah",
    "protein": [
      "beef"
    ],
    "heat": 3,
    "signature": false,
    "story": "The family says they made more of it during the 1940s occupation.",
    "pairs": [
      "murtabak",
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S1, S3, S7",
    "verify": []
  },
  {
    "slug": "rendang-daging",
    "en": "Beef rendang",
    "ms": "Rendang Daging",
    "tray": "kuah",
    "protein": [
      "beef"
    ],
    "heat": 3,
    "signature": false,
    "story": "Slow-cooked until the gravy clings to the meat.",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S1, S3, S6",
    "verify": []
  },
  {
    "slug": "daging-masak-hitam",
    "en": "Beef in dark soy gravy",
    "ms": "Daging Masak Hitam",
    "tray": "kuah",
    "protein": [
      "beef"
    ],
    "heat": 2,
    "signature": false,
    "story": "On the plate the family remembers selling for 20 to 30 sen.",
    "pairs": [
      "nasi-kandar",
      "bendi"
    ],
    "price": "Ask at counter",
    "source": "S5",
    "verify": []
  },
  {
    "slug": "mutton-mysore",
    "en": "Mutton Mysore",
    "ms": "Kambing Mysore",
    "tray": "kuah",
    "protein": [
      "mutton"
    ],
    "heat": 4,
    "signature": false,
    "story": "A dry, peppery mutton fry, and a house favourite.",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S3",
    "verify": []
  },
  {
    "slug": "kari-kambing",
    "en": "Mutton curry",
    "ms": "Kari Kambing",
    "tray": "kuah",
    "protein": [
      "mutton"
    ],
    "heat": 3,
    "signature": false,
    "story": "Thick and deeply spiced.",
    "pairs": [
      "nasi-briyani"
    ],
    "price": "Ask at counter",
    "source": "S6, S7",
    "verify": []
  },
  {
    "slug": "lamb-shank",
    "en": "Lamb shank",
    "ms": "Kambing Shank",
    "tray": "kuah",
    "protein": [
      "mutton"
    ],
    "heat": 2,
    "signature": false,
    "story": "A whole shank in the house masala.",
    "pairs": [
      "nasi-briyani"
    ],
    "price": "Ask at counter",
    "source": "S8, S9",
    "verify": []
  },
  {
    "slug": "kari-ayam-belanda",
    "en": "Turkey curry",
    "ms": "Kari Ayam Belanda",
    "tray": "kuah",
    "protein": [
      "chicken"
    ],
    "heat": 3,
    "signature": false,
    "story": "Giant turkey legs in curry, a Hameediyah oddity worth the photo.",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S5, S6",
    "verify": []
  },
  {
    "slug": "ayam-masak-ros",
    "en": "Chicken in rose gravy",
    "ms": "Ayam Masak Ros",
    "tray": "kuah",
    "protein": [
      "chicken"
    ],
    "heat": 1,
    "signature": false,
    "story": "Mild, sweet-tomato gravy for those who want less heat.",
    "pairs": [
      "nasi-tomato"
    ],
    "price": "Ask at counter",
    "source": "S5",
    "verify": []
  },
  {
    "slug": "kari-itik",
    "en": "Duck curry",
    "ms": "Kari Itik",
    "tray": "kuah",
    "protein": [
      "chicken"
    ],
    "heat": 3,
    "signature": false,
    "story": "Duck drumsticks in the house spice blend.",
    "pairs": [
      "nasi-tomato"
    ],
    "price": "Ask at counter",
    "source": "S7, S8",
    "verify": []
  },
  {
    "slug": "dalca",
    "en": "Dhal curry",
    "ms": "Dalca",
    "tray": "kuah",
    "protein": [
      "vegetarian"
    ],
    "heat": 2,
    "signature": false,
    "story": "Lentils and vegetables; the family's dhal recipe is a century old.",
    "pairs": [
      "murtabak",
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S3, S7",
    "verify": []
  },
  {
    "slug": "kari-kepala-ikan",
    "en": "Fish-head curry",
    "ms": "Kari Kepala Ikan",
    "tray": "laut",
    "protein": [
      "seafood"
    ],
    "heat": 4,
    "signature": false,
    "story": "A whole fish head in a sour, spiced kuah. Big enough to share.",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S7, S8, SPEC §14.5",
    "verify": []
  },
  {
    "slug": "kari-ikan",
    "en": "Fish curry",
    "ms": "Kari Ikan",
    "tray": "laut",
    "protein": [
      "seafood"
    ],
    "heat": 3,
    "signature": false,
    "story": "On the 20-to-30-sen plate the family remembers from the old days.",
    "pairs": [
      "nasi-kandar",
      "bendi"
    ],
    "price": "Ask at counter",
    "source": "S5",
    "verify": []
  },
  {
    "slug": "kari-sotong",
    "en": "Squid curry",
    "ms": "Kari Sotong",
    "tray": "laut",
    "protein": [
      "seafood"
    ],
    "heat": 3,
    "signature": false,
    "story": "Tender squid in a red curry.",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S7",
    "verify": []
  },
  {
    "slug": "telur-ikan",
    "en": "Fish roe",
    "ms": "Telur Ikan",
    "tray": "laut",
    "protein": [
      "seafood"
    ],
    "heat": 2,
    "signature": false,
    "story": "Fried roe, one of the lesser-known house signatures.",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S3",
    "verify": []
  },
  {
    "slug": "sotong-goreng",
    "en": "Fried squid",
    "ms": "Sotong Goreng",
    "tray": "goreng",
    "protein": [
      "seafood"
    ],
    "heat": 2,
    "signature": false,
    "story": "A best-seller: crisp, spiced squid.",
    "pairs": [
      "nasi-kandar",
      "kuah-campur"
    ],
    "price": "Ask at counter",
    "source": "S8, S9",
    "verify": []
  },
  {
    "slug": "ayam-goreng",
    "en": "Fried chicken",
    "ms": "Ayam Goreng",
    "tray": "goreng",
    "protein": [
      "chicken"
    ],
    "heat": 2,
    "signature": false,
    "story": "Marinated in spices, fried crisp, still juicy inside.",
    "pairs": [
      "nasi-briyani"
    ],
    "price": "Ask at counter",
    "source": "S6, S9",
    "verify": []
  },
  {
    "slug": "ayam-rempah",
    "en": "Spice-rubbed chicken",
    "ms": "Ayam Rempah",
    "tray": "goreng",
    "protein": [
      "chicken"
    ],
    "heat": 3,
    "signature": false,
    "story": "Chicken fried in a thick rempah (spice paste).",
    "pairs": [
      "nasi-kandar"
    ],
    "price": "Ask at counter",
    "source": "S7",
    "verify": []
  },
  {
    "slug": "mee-goreng",
    "en": "Fried noodles",
    "ms": "Mee Goreng",
    "tray": "goreng",
    "protein": [
      "seafood"
    ],
    "heat": 3,
    "signature": false,
    "story": "Wok-fried noodles; a long-time favourite.",
    "pairs": [
      "iced-lemon-tea"
    ],
    "price": "Ask at counter",
    "source": "S1, S8",
    "verify": []
  },
  {
    "slug": "tandoori-ayam",
    "en": "Tandoori chicken",
    "ms": "Ayam Tandoori",
    "tray": "goreng",
    "protein": [
      "chicken"
    ],
    "heat": 2,
    "signature": false,
    "story": "From Hameediyah Tandoori House, two doors down.",
    "pairs": [
      "roti-naan"
    ],
    "price": "Ask at counter",
    "source": "S1, S8",
    "verify": []
  },
  {
    "slug": "roti-naan",
    "en": "Naan",
    "ms": "Roti Naan",
    "tray": "roti",
    "protein": [
      "vegetarian"
    ],
    "heat": 1,
    "signature": false,
    "story": "Soft naan straight from the tandoor.",
    "pairs": [
      "tandoori-ayam",
      "mutton-kurma"
    ],
    "price": "Ask at counter",
    "source": "S8",
    "verify": []
  },
  {
    "slug": "teh-tarik",
    "en": "Pulled milk tea",
    "ms": "Teh Tarik",
    "tray": "minum",
    "protein": [
      "vegetarian"
    ],
    "heat": 1,
    "signature": false,
    "story": "Sweet milk tea, poured from a height until it froths.",
    "pairs": [
      "murtabak"
    ],
    "price": "Ask at counter",
    "source": "SPEC §7 MN-01 (example)",
    "verify": []
  },
  {
    "slug": "iced-lemon-tea",
    "en": "Iced lemon tea",
    "ms": "Teh O Ais Limau",
    "tray": "minum",
    "protein": [
      "vegetarian"
    ],
    "heat": 1,
    "signature": false,
    "story": "Strong, not too sweet: the cool-down after the kuah.",
    "pairs": [
      "mee-goreng",
      "nasi-briyani"
    ],
    "price": "Ask at counter",
    "source": "S9",
    "verify": []
  }
] as Dish[]
